/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PermissionRouteImport } from './routes/permission'
import { Route as UnauthorizeRouteImport } from './routes/_unauthorize'
import { Route as AuthorizeRouteImport } from './routes/_authorize'
import { Route as AuthorizeIndexRouteImport } from './routes/_authorize/index'
import { Route as AuthorizeDevRouteImport } from './routes/_authorize/dev'
import { Route as UnauthorizeLoginIndexRouteImport } from './routes/_unauthorize/login/index'
import { Route as AuthorizeUsersIndexRouteImport } from './routes/_authorize/users/index'
import { Route as AuthorizeProductManagementIndexRouteImport } from './routes/_authorize/product-management/index'
import { Route as AuthorizeDashboardIndexRouteImport } from './routes/_authorize/dashboard/index'
import { Route as AuthorizeUsersCreateRouteImport } from './routes/_authorize/users/create'
import { Route as AuthorizeLogsExportTransactionsRouteImport } from './routes/_authorize/logs/export-transactions'
import { Route as AuthorizeProductManagementPrintsRouteRouteImport } from './routes/_authorize/product-management/prints/route'
import { Route as AuthorizeProductManagementAttributesRouteRouteImport } from './routes/_authorize/product-management/attributes/route'
import { Route as AuthorizeSystemTeamsIndexRouteImport } from './routes/_authorize/system/teams/index'
import { Route as AuthorizeSystemPermissionsIndexRouteImport } from './routes/_authorize/system/permissions/index'
import { Route as AuthorizeSystemMembersIndexRouteImport } from './routes/_authorize/system/members/index'
import { Route as AuthorizeProductManagementVariantsIndexRouteImport } from './routes/_authorize/product-management/variants/index'
import { Route as AuthorizeProductManagementProductsIndexRouteImport } from './routes/_authorize/product-management/products/index'
import { Route as AuthorizeProductManagementPrintsIndexRouteImport } from './routes/_authorize/product-management/prints/index'
import { Route as AuthorizeProductManagementOptionsIndexRouteImport } from './routes/_authorize/product-management/options/index'
import { Route as AuthorizeProductManagementCategoriesIndexRouteImport } from './routes/_authorize/product-management/categories/index'
import { Route as AuthorizeProductManagementAttributesIndexRouteImport } from './routes/_authorize/product-management/attributes/index'
import { Route as AuthorizeOrderSaleOrdersIndexRouteImport } from './routes/_authorize/order/sale-orders/index'
import { Route as AuthorizeOrderErrorOrdersIndexRouteImport } from './routes/_authorize/order/error-orders/index'
import { Route as AuthorizeOrderDraftOrdersIndexRouteImport } from './routes/_authorize/order/draft-orders/index'
import { Route as AuthorizeOrderAllOrdersIndexRouteImport } from './routes/_authorize/order/all-orders/index'
import { Route as AuthorizeOrderOrderIdIndexRouteImport } from './routes/_authorize/order/$orderId/index'
import { Route as AuthorizeLogsPaymentLogsIndexRouteImport } from './routes/_authorize/logs/payment-logs/index'
import { Route as AuthorizeLogsExportTransactionsIndexRouteImport } from './routes/_authorize/logs/export-transactions/index'
import { Route as AuthorizeLogsCallLogsIndexRouteImport } from './routes/_authorize/logs/call-logs/index'
import { Route as AuthorizeGlobalConfigurationTierManagementIndexRouteImport } from './routes/_authorize/global-configuration/tier-management/index'
import { Route as AuthorizeGlobalConfigurationRushOrderIndexRouteImport } from './routes/_authorize/global-configuration/rush-order/index'
import { Route as AuthorizeGlobalConfigurationPricingManagementIndexRouteImport } from './routes/_authorize/global-configuration/pricing-management/index'
import { Route as AuthorizeGlobalConfigurationFinanceIndexRouteImport } from './routes/_authorize/global-configuration/finance/index'
import { Route as AuthorizeFulfillmentTransactionsIndexRouteImport } from './routes/_authorize/fulfillment/transactions/index'
import { Route as AuthorizeFulfillmentShippingPlansIndexRouteImport } from './routes/_authorize/fulfillment/shipping-plans/index'
import { Route as AuthorizeFinanceTransactionsIndexRouteImport } from './routes/_authorize/finance/transactions/index'
import { Route as AuthorizeFinancePaymentRequestIndexRouteImport } from './routes/_authorize/finance/payment-request/index'
import { Route as AuthorizeFinanceDepositIndexRouteImport } from './routes/_authorize/finance/deposit/index'
import { Route as AuthorizeDevSyncIndexRouteImport } from './routes/_authorize/dev/sync/index'
import { Route as AuthorizeDevOpenFeaturesIndexRouteImport } from './routes/_authorize/dev/open-features/index'
import { Route as AuthorizeDevMigrationIndexRouteImport } from './routes/_authorize/dev/migration/index'
import { Route as AuthorizeSystemMembersPermissionRouteImport } from './routes/_authorize/system/members/permission'
import { Route as AuthorizeSystemMembersNewUserRouteImport } from './routes/_authorize/system/members/new-user'
import { Route as AuthorizeGlobalConfigurationTierManagementUpdateTeamTierRouteImport } from './routes/_authorize/global-configuration/tier-management/update-team-tier'
import { Route as AuthorizeGlobalConfigurationTierManagementTierUpdateLogsRouteImport } from './routes/_authorize/global-configuration/tier-management/tier-update-logs'
import { Route as AuthorizeGlobalConfigurationPricingManagementCreatePricingRuleRouteImport } from './routes/_authorize/global-configuration/pricing-management/create-pricing-rule'
import { Route as AuthorizeSystemTeamsTeamIdIndexRouteImport } from './routes/_authorize/system/teams/$teamId/index'
import { Route as AuthorizeProductManagementProductsProductIdIndexRouteImport } from './routes/_authorize/product-management/products/$productId/index'
import { Route as AuthorizeProductManagementPrintsTypeIndexRouteImport } from './routes/_authorize/product-management/prints/type/index'
import { Route as AuthorizeProductManagementPrintsLocationIndexRouteImport } from './routes/_authorize/product-management/prints/location/index'
import { Route as AuthorizeProductManagementCategoriesCategoryIdIndexRouteImport } from './routes/_authorize/product-management/categories/$categoryId/index'
import { Route as AuthorizeProductManagementAttributesLibraryIndexRouteImport } from './routes/_authorize/product-management/attributes/library/index'
import { Route as AuthorizeProductManagementAttributesGroupIndexRouteImport } from './routes/_authorize/product-management/attributes/group/index'
import { Route as AuthorizeOrderDraftOrdersOrderIdIndexRouteImport } from './routes/_authorize/order/draft-orders/$orderId/index'
import { Route as AuthorizeGlobalConfigurationPricingManagementCustomIdIndexRouteImport } from './routes/_authorize/global-configuration/pricing-management/$customId/index'
import { Route as AuthorizeFinanceTransactionsTransactionIdIndexRouteImport } from './routes/_authorize/finance/transactions/$transactionId/index'
import { Route as AuthorizeSystemTeamsTeamIdTransactionsIndexRouteImport } from './routes/_authorize/system/teams/$teamId/transactions/index'
import { Route as AuthorizeSystemTeamsTeamIdStoreIndexRouteImport } from './routes/_authorize/system/teams/$teamId/store/index'
import { Route as AuthorizeSystemTeamsTeamIdPaymentMethodsIndexRouteImport } from './routes/_authorize/system/teams/$teamId/payment-methods/index'
import { Route as AuthorizeSystemTeamsTeamIdGCreditsIndexRouteImport } from './routes/_authorize/system/teams/$teamId/g-credits/index'
import { Route as AuthorizeSystemTeamsTeamIdDetailsIndexRouteImport } from './routes/_authorize/system/teams/$teamId/details/index'
import { Route as AuthorizeProductManagementPrintsTypeTypeIdIndexRouteImport } from './routes/_authorize/product-management/prints/type/$typeId/index'
import { Route as AuthorizeProductManagementPrintsLocationLocationIdIndexRouteImport } from './routes/_authorize/product-management/prints/location/$locationId/index'
import { Route as AuthorizeProductManagementAttributesLibraryLibraryIdIndexRouteImport } from './routes/_authorize/product-management/attributes/library/$libraryId/index'
import { Route as AuthorizeProductManagementAttributesGroupGroupIdIndexRouteImport } from './routes/_authorize/product-management/attributes/group/$groupId/index'
import { Route as AuthorizeFulfillmentShippingPlansshippingDetailShippingIdIndexRouteImport } from './routes/_authorize/fulfillment/shipping-plans/(shipping-detail)/$shippingId/index'
import { Route as AuthorizeFinanceTransactionsTransactionIdInvoiceIndexRouteImport } from './routes/_authorize/finance/transactions/$transactionId/invoice/index'
import { Route as AuthorizeSystemTeamsTeamIdGCreditsEnableRouteImport } from './routes/_authorize/system/teams/$teamId/g-credits/enable'
import { Route as AuthorizeSystemTeamsTeamIdTransactionsTxnIdIndexRouteImport } from './routes/_authorize/system/teams/$teamId/transactions/$txnId/index'
import { Route as AuthorizeSystemTeamsTeamIdStoreStoreIdIndexRouteImport } from './routes/_authorize/system/teams/$teamId/store/$storeId/index'
import { Route as AuthorizeSystemTeamsTeamIdLogsImportOrdersIndexRouteImport } from './routes/_authorize/system/teams/$teamId/logs/import-orders/index'
import { Route as AuthorizeSystemTeamsTeamIdconfigPrintTypeIndexRouteImport } from './routes/_authorize/system/teams/$teamId/(config)/print-type/index'
import { Route as AuthorizeSystemTeamsTeamIdconfigGeneralIndexRouteImport } from './routes/_authorize/system/teams/$teamId/(config)/general/index'

const PermissionRoute = PermissionRouteImport.update({
  id: '/permission',
  path: '/permission',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizeRoute = UnauthorizeRouteImport.update({
  id: '/_unauthorize',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizeRoute = AuthorizeRouteImport.update({
  id: '/_authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizeIndexRoute = AuthorizeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthorizeRoute,
} as any)
const AuthorizeDevRoute = AuthorizeDevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => AuthorizeRoute,
} as any)
const UnauthorizeLoginIndexRoute = UnauthorizeLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => UnauthorizeRoute,
} as any)
const AuthorizeUsersIndexRoute = AuthorizeUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthorizeRoute,
} as any)
const AuthorizeProductManagementIndexRoute =
  AuthorizeProductManagementIndexRouteImport.update({
    id: '/product-management/',
    path: '/product-management/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeDashboardIndexRoute = AuthorizeDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthorizeRoute,
} as any)
const AuthorizeUsersCreateRoute = AuthorizeUsersCreateRouteImport.update({
  id: '/users/create',
  path: '/users/create',
  getParentRoute: () => AuthorizeRoute,
} as any)
const AuthorizeLogsExportTransactionsRoute =
  AuthorizeLogsExportTransactionsRouteImport.update({
    id: '/logs/export-transactions',
    path: '/logs/export-transactions',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeProductManagementPrintsRouteRoute =
  AuthorizeProductManagementPrintsRouteRouteImport.update({
    id: '/product-management/prints',
    path: '/product-management/prints',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeProductManagementAttributesRouteRoute =
  AuthorizeProductManagementAttributesRouteRouteImport.update({
    id: '/product-management/attributes',
    path: '/product-management/attributes',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeSystemTeamsIndexRoute =
  AuthorizeSystemTeamsIndexRouteImport.update({
    id: '/system/teams/',
    path: '/system/teams/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeSystemPermissionsIndexRoute =
  AuthorizeSystemPermissionsIndexRouteImport.update({
    id: '/system/permissions/',
    path: '/system/permissions/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeSystemMembersIndexRoute =
  AuthorizeSystemMembersIndexRouteImport.update({
    id: '/system/members/',
    path: '/system/members/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeProductManagementVariantsIndexRoute =
  AuthorizeProductManagementVariantsIndexRouteImport.update({
    id: '/product-management/variants/',
    path: '/product-management/variants/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeProductManagementProductsIndexRoute =
  AuthorizeProductManagementProductsIndexRouteImport.update({
    id: '/product-management/products/',
    path: '/product-management/products/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeProductManagementPrintsIndexRoute =
  AuthorizeProductManagementPrintsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthorizeProductManagementPrintsRouteRoute,
  } as any)
const AuthorizeProductManagementOptionsIndexRoute =
  AuthorizeProductManagementOptionsIndexRouteImport.update({
    id: '/product-management/options/',
    path: '/product-management/options/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeProductManagementCategoriesIndexRoute =
  AuthorizeProductManagementCategoriesIndexRouteImport.update({
    id: '/product-management/categories/',
    path: '/product-management/categories/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeProductManagementAttributesIndexRoute =
  AuthorizeProductManagementAttributesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthorizeProductManagementAttributesRouteRoute,
  } as any)
const AuthorizeOrderSaleOrdersIndexRoute =
  AuthorizeOrderSaleOrdersIndexRouteImport.update({
    id: '/order/sale-orders/',
    path: '/order/sale-orders/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeOrderErrorOrdersIndexRoute =
  AuthorizeOrderErrorOrdersIndexRouteImport.update({
    id: '/order/error-orders/',
    path: '/order/error-orders/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeOrderDraftOrdersIndexRoute =
  AuthorizeOrderDraftOrdersIndexRouteImport.update({
    id: '/order/draft-orders/',
    path: '/order/draft-orders/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeOrderAllOrdersIndexRoute =
  AuthorizeOrderAllOrdersIndexRouteImport.update({
    id: '/order/all-orders/',
    path: '/order/all-orders/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeOrderOrderIdIndexRoute =
  AuthorizeOrderOrderIdIndexRouteImport.update({
    id: '/order/$orderId/',
    path: '/order/$orderId/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeLogsPaymentLogsIndexRoute =
  AuthorizeLogsPaymentLogsIndexRouteImport.update({
    id: '/logs/payment-logs/',
    path: '/logs/payment-logs/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeLogsExportTransactionsIndexRoute =
  AuthorizeLogsExportTransactionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthorizeLogsExportTransactionsRoute,
  } as any)
const AuthorizeLogsCallLogsIndexRoute =
  AuthorizeLogsCallLogsIndexRouteImport.update({
    id: '/logs/call-logs/',
    path: '/logs/call-logs/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeGlobalConfigurationTierManagementIndexRoute =
  AuthorizeGlobalConfigurationTierManagementIndexRouteImport.update({
    id: '/global-configuration/tier-management/',
    path: '/global-configuration/tier-management/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeGlobalConfigurationRushOrderIndexRoute =
  AuthorizeGlobalConfigurationRushOrderIndexRouteImport.update({
    id: '/global-configuration/rush-order/',
    path: '/global-configuration/rush-order/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeGlobalConfigurationPricingManagementIndexRoute =
  AuthorizeGlobalConfigurationPricingManagementIndexRouteImport.update({
    id: '/global-configuration/pricing-management/',
    path: '/global-configuration/pricing-management/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeGlobalConfigurationFinanceIndexRoute =
  AuthorizeGlobalConfigurationFinanceIndexRouteImport.update({
    id: '/global-configuration/finance/',
    path: '/global-configuration/finance/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeFulfillmentTransactionsIndexRoute =
  AuthorizeFulfillmentTransactionsIndexRouteImport.update({
    id: '/fulfillment/transactions/',
    path: '/fulfillment/transactions/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeFulfillmentShippingPlansIndexRoute =
  AuthorizeFulfillmentShippingPlansIndexRouteImport.update({
    id: '/fulfillment/shipping-plans/',
    path: '/fulfillment/shipping-plans/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeFinanceTransactionsIndexRoute =
  AuthorizeFinanceTransactionsIndexRouteImport.update({
    id: '/finance/transactions/',
    path: '/finance/transactions/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeFinancePaymentRequestIndexRoute =
  AuthorizeFinancePaymentRequestIndexRouteImport.update({
    id: '/finance/payment-request/',
    path: '/finance/payment-request/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeFinanceDepositIndexRoute =
  AuthorizeFinanceDepositIndexRouteImport.update({
    id: '/finance/deposit/',
    path: '/finance/deposit/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeDevSyncIndexRoute = AuthorizeDevSyncIndexRouteImport.update({
  id: '/sync/',
  path: '/sync/',
  getParentRoute: () => AuthorizeDevRoute,
} as any)
const AuthorizeDevOpenFeaturesIndexRoute =
  AuthorizeDevOpenFeaturesIndexRouteImport.update({
    id: '/open-features/',
    path: '/open-features/',
    getParentRoute: () => AuthorizeDevRoute,
  } as any)
const AuthorizeDevMigrationIndexRoute =
  AuthorizeDevMigrationIndexRouteImport.update({
    id: '/migration/',
    path: '/migration/',
    getParentRoute: () => AuthorizeDevRoute,
  } as any)
const AuthorizeSystemMembersPermissionRoute =
  AuthorizeSystemMembersPermissionRouteImport.update({
    id: '/system/members/permission',
    path: '/system/members/permission',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeSystemMembersNewUserRoute =
  AuthorizeSystemMembersNewUserRouteImport.update({
    id: '/system/members/new-user',
    path: '/system/members/new-user',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeGlobalConfigurationTierManagementUpdateTeamTierRoute =
  AuthorizeGlobalConfigurationTierManagementUpdateTeamTierRouteImport.update({
    id: '/global-configuration/tier-management/update-team-tier',
    path: '/global-configuration/tier-management/update-team-tier',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeGlobalConfigurationTierManagementTierUpdateLogsRoute =
  AuthorizeGlobalConfigurationTierManagementTierUpdateLogsRouteImport.update({
    id: '/global-configuration/tier-management/tier-update-logs',
    path: '/global-configuration/tier-management/tier-update-logs',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeGlobalConfigurationPricingManagementCreatePricingRuleRoute =
  AuthorizeGlobalConfigurationPricingManagementCreatePricingRuleRouteImport.update(
    {
      id: '/global-configuration/pricing-management/create-pricing-rule',
      path: '/global-configuration/pricing-management/create-pricing-rule',
      getParentRoute: () => AuthorizeRoute,
    } as any,
  )
const AuthorizeSystemTeamsTeamIdIndexRoute =
  AuthorizeSystemTeamsTeamIdIndexRouteImport.update({
    id: '/system/teams/$teamId/',
    path: '/system/teams/$teamId/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeProductManagementProductsProductIdIndexRoute =
  AuthorizeProductManagementProductsProductIdIndexRouteImport.update({
    id: '/product-management/products/$productId/',
    path: '/product-management/products/$productId/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeProductManagementPrintsTypeIndexRoute =
  AuthorizeProductManagementPrintsTypeIndexRouteImport.update({
    id: '/type/',
    path: '/type/',
    getParentRoute: () => AuthorizeProductManagementPrintsRouteRoute,
  } as any)
const AuthorizeProductManagementPrintsLocationIndexRoute =
  AuthorizeProductManagementPrintsLocationIndexRouteImport.update({
    id: '/location/',
    path: '/location/',
    getParentRoute: () => AuthorizeProductManagementPrintsRouteRoute,
  } as any)
const AuthorizeProductManagementCategoriesCategoryIdIndexRoute =
  AuthorizeProductManagementCategoriesCategoryIdIndexRouteImport.update({
    id: '/product-management/categories/$categoryId/',
    path: '/product-management/categories/$categoryId/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeProductManagementAttributesLibraryIndexRoute =
  AuthorizeProductManagementAttributesLibraryIndexRouteImport.update({
    id: '/library/',
    path: '/library/',
    getParentRoute: () => AuthorizeProductManagementAttributesRouteRoute,
  } as any)
const AuthorizeProductManagementAttributesGroupIndexRoute =
  AuthorizeProductManagementAttributesGroupIndexRouteImport.update({
    id: '/group/',
    path: '/group/',
    getParentRoute: () => AuthorizeProductManagementAttributesRouteRoute,
  } as any)
const AuthorizeOrderDraftOrdersOrderIdIndexRoute =
  AuthorizeOrderDraftOrdersOrderIdIndexRouteImport.update({
    id: '/order/draft-orders/$orderId/',
    path: '/order/draft-orders/$orderId/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeGlobalConfigurationPricingManagementCustomIdIndexRoute =
  AuthorizeGlobalConfigurationPricingManagementCustomIdIndexRouteImport.update({
    id: '/global-configuration/pricing-management/$customId/',
    path: '/global-configuration/pricing-management/$customId/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeFinanceTransactionsTransactionIdIndexRoute =
  AuthorizeFinanceTransactionsTransactionIdIndexRouteImport.update({
    id: '/finance/transactions/$transactionId/',
    path: '/finance/transactions/$transactionId/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeSystemTeamsTeamIdTransactionsIndexRoute =
  AuthorizeSystemTeamsTeamIdTransactionsIndexRouteImport.update({
    id: '/system/teams/$teamId/transactions/',
    path: '/system/teams/$teamId/transactions/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeSystemTeamsTeamIdStoreIndexRoute =
  AuthorizeSystemTeamsTeamIdStoreIndexRouteImport.update({
    id: '/system/teams/$teamId/store/',
    path: '/system/teams/$teamId/store/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeSystemTeamsTeamIdPaymentMethodsIndexRoute =
  AuthorizeSystemTeamsTeamIdPaymentMethodsIndexRouteImport.update({
    id: '/system/teams/$teamId/payment-methods/',
    path: '/system/teams/$teamId/payment-methods/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeSystemTeamsTeamIdGCreditsIndexRoute =
  AuthorizeSystemTeamsTeamIdGCreditsIndexRouteImport.update({
    id: '/system/teams/$teamId/g-credits/',
    path: '/system/teams/$teamId/g-credits/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeSystemTeamsTeamIdDetailsIndexRoute =
  AuthorizeSystemTeamsTeamIdDetailsIndexRouteImport.update({
    id: '/system/teams/$teamId/details/',
    path: '/system/teams/$teamId/details/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeProductManagementPrintsTypeTypeIdIndexRoute =
  AuthorizeProductManagementPrintsTypeTypeIdIndexRouteImport.update({
    id: '/type/$typeId/',
    path: '/type/$typeId/',
    getParentRoute: () => AuthorizeProductManagementPrintsRouteRoute,
  } as any)
const AuthorizeProductManagementPrintsLocationLocationIdIndexRoute =
  AuthorizeProductManagementPrintsLocationLocationIdIndexRouteImport.update({
    id: '/location/$locationId/',
    path: '/location/$locationId/',
    getParentRoute: () => AuthorizeProductManagementPrintsRouteRoute,
  } as any)
const AuthorizeProductManagementAttributesLibraryLibraryIdIndexRoute =
  AuthorizeProductManagementAttributesLibraryLibraryIdIndexRouteImport.update({
    id: '/library/$libraryId/',
    path: '/library/$libraryId/',
    getParentRoute: () => AuthorizeProductManagementAttributesRouteRoute,
  } as any)
const AuthorizeProductManagementAttributesGroupGroupIdIndexRoute =
  AuthorizeProductManagementAttributesGroupGroupIdIndexRouteImport.update({
    id: '/group/$groupId/',
    path: '/group/$groupId/',
    getParentRoute: () => AuthorizeProductManagementAttributesRouteRoute,
  } as any)
const AuthorizeFulfillmentShippingPlansshippingDetailShippingIdIndexRoute =
  AuthorizeFulfillmentShippingPlansshippingDetailShippingIdIndexRouteImport.update(
    {
      id: '/fulfillment/shipping-plans/(shipping-detail)/$shippingId/',
      path: '/fulfillment/shipping-plans/$shippingId/',
      getParentRoute: () => AuthorizeRoute,
    } as any,
  )
const AuthorizeFinanceTransactionsTransactionIdInvoiceIndexRoute =
  AuthorizeFinanceTransactionsTransactionIdInvoiceIndexRouteImport.update({
    id: '/finance/transactions/$transactionId/invoice/',
    path: '/finance/transactions/$transactionId/invoice/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeSystemTeamsTeamIdGCreditsEnableRoute =
  AuthorizeSystemTeamsTeamIdGCreditsEnableRouteImport.update({
    id: '/system/teams/$teamId/g-credits/enable',
    path: '/system/teams/$teamId/g-credits/enable',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeSystemTeamsTeamIdTransactionsTxnIdIndexRoute =
  AuthorizeSystemTeamsTeamIdTransactionsTxnIdIndexRouteImport.update({
    id: '/system/teams/$teamId/transactions/$txnId/',
    path: '/system/teams/$teamId/transactions/$txnId/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeSystemTeamsTeamIdStoreStoreIdIndexRoute =
  AuthorizeSystemTeamsTeamIdStoreStoreIdIndexRouteImport.update({
    id: '/system/teams/$teamId/store/$storeId/',
    path: '/system/teams/$teamId/store/$storeId/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeSystemTeamsTeamIdLogsImportOrdersIndexRoute =
  AuthorizeSystemTeamsTeamIdLogsImportOrdersIndexRouteImport.update({
    id: '/system/teams/$teamId/logs/import-orders/',
    path: '/system/teams/$teamId/logs/import-orders/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeSystemTeamsTeamIdconfigPrintTypeIndexRoute =
  AuthorizeSystemTeamsTeamIdconfigPrintTypeIndexRouteImport.update({
    id: '/system/teams/$teamId/(config)/print-type/',
    path: '/system/teams/$teamId/print-type/',
    getParentRoute: () => AuthorizeRoute,
  } as any)
const AuthorizeSystemTeamsTeamIdconfigGeneralIndexRoute =
  AuthorizeSystemTeamsTeamIdconfigGeneralIndexRouteImport.update({
    id: '/system/teams/$teamId/(config)/general/',
    path: '/system/teams/$teamId/general/',
    getParentRoute: () => AuthorizeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthorizeIndexRoute
  '/permission': typeof PermissionRoute
  '/dev': typeof AuthorizeDevRouteWithChildren
  '/product-management/attributes': typeof AuthorizeProductManagementAttributesRouteRouteWithChildren
  '/product-management/prints': typeof AuthorizeProductManagementPrintsRouteRouteWithChildren
  '/logs/export-transactions': typeof AuthorizeLogsExportTransactionsRouteWithChildren
  '/users/create': typeof AuthorizeUsersCreateRoute
  '/dashboard/': typeof AuthorizeDashboardIndexRoute
  '/product-management/': typeof AuthorizeProductManagementIndexRoute
  '/users/': typeof AuthorizeUsersIndexRoute
  '/login/': typeof UnauthorizeLoginIndexRoute
  '/global-configuration/pricing-management/create-pricing-rule': typeof AuthorizeGlobalConfigurationPricingManagementCreatePricingRuleRoute
  '/global-configuration/tier-management/tier-update-logs': typeof AuthorizeGlobalConfigurationTierManagementTierUpdateLogsRoute
  '/global-configuration/tier-management/update-team-tier': typeof AuthorizeGlobalConfigurationTierManagementUpdateTeamTierRoute
  '/system/members/new-user': typeof AuthorizeSystemMembersNewUserRoute
  '/system/members/permission': typeof AuthorizeSystemMembersPermissionRoute
  '/dev/migration/': typeof AuthorizeDevMigrationIndexRoute
  '/dev/open-features/': typeof AuthorizeDevOpenFeaturesIndexRoute
  '/dev/sync/': typeof AuthorizeDevSyncIndexRoute
  '/finance/deposit/': typeof AuthorizeFinanceDepositIndexRoute
  '/finance/payment-request/': typeof AuthorizeFinancePaymentRequestIndexRoute
  '/finance/transactions/': typeof AuthorizeFinanceTransactionsIndexRoute
  '/fulfillment/shipping-plans/': typeof AuthorizeFulfillmentShippingPlansIndexRoute
  '/fulfillment/transactions/': typeof AuthorizeFulfillmentTransactionsIndexRoute
  '/global-configuration/finance/': typeof AuthorizeGlobalConfigurationFinanceIndexRoute
  '/global-configuration/pricing-management/': typeof AuthorizeGlobalConfigurationPricingManagementIndexRoute
  '/global-configuration/rush-order/': typeof AuthorizeGlobalConfigurationRushOrderIndexRoute
  '/global-configuration/tier-management/': typeof AuthorizeGlobalConfigurationTierManagementIndexRoute
  '/logs/call-logs/': typeof AuthorizeLogsCallLogsIndexRoute
  '/logs/export-transactions/': typeof AuthorizeLogsExportTransactionsIndexRoute
  '/logs/payment-logs/': typeof AuthorizeLogsPaymentLogsIndexRoute
  '/order/$orderId/': typeof AuthorizeOrderOrderIdIndexRoute
  '/order/all-orders/': typeof AuthorizeOrderAllOrdersIndexRoute
  '/order/draft-orders/': typeof AuthorizeOrderDraftOrdersIndexRoute
  '/order/error-orders/': typeof AuthorizeOrderErrorOrdersIndexRoute
  '/order/sale-orders/': typeof AuthorizeOrderSaleOrdersIndexRoute
  '/product-management/attributes/': typeof AuthorizeProductManagementAttributesIndexRoute
  '/product-management/categories/': typeof AuthorizeProductManagementCategoriesIndexRoute
  '/product-management/options/': typeof AuthorizeProductManagementOptionsIndexRoute
  '/product-management/prints/': typeof AuthorizeProductManagementPrintsIndexRoute
  '/product-management/products/': typeof AuthorizeProductManagementProductsIndexRoute
  '/product-management/variants/': typeof AuthorizeProductManagementVariantsIndexRoute
  '/system/members/': typeof AuthorizeSystemMembersIndexRoute
  '/system/permissions/': typeof AuthorizeSystemPermissionsIndexRoute
  '/system/teams/': typeof AuthorizeSystemTeamsIndexRoute
  '/finance/transactions/$transactionId/': typeof AuthorizeFinanceTransactionsTransactionIdIndexRoute
  '/global-configuration/pricing-management/$customId/': typeof AuthorizeGlobalConfigurationPricingManagementCustomIdIndexRoute
  '/order/draft-orders/$orderId/': typeof AuthorizeOrderDraftOrdersOrderIdIndexRoute
  '/product-management/attributes/group/': typeof AuthorizeProductManagementAttributesGroupIndexRoute
  '/product-management/attributes/library/': typeof AuthorizeProductManagementAttributesLibraryIndexRoute
  '/product-management/categories/$categoryId/': typeof AuthorizeProductManagementCategoriesCategoryIdIndexRoute
  '/product-management/prints/location/': typeof AuthorizeProductManagementPrintsLocationIndexRoute
  '/product-management/prints/type/': typeof AuthorizeProductManagementPrintsTypeIndexRoute
  '/product-management/products/$productId/': typeof AuthorizeProductManagementProductsProductIdIndexRoute
  '/system/teams/$teamId/': typeof AuthorizeSystemTeamsTeamIdIndexRoute
  '/system/teams/$teamId/g-credits/enable': typeof AuthorizeSystemTeamsTeamIdGCreditsEnableRoute
  '/finance/transactions/$transactionId/invoice/': typeof AuthorizeFinanceTransactionsTransactionIdInvoiceIndexRoute
  '/fulfillment/shipping-plans/$shippingId/': typeof AuthorizeFulfillmentShippingPlansshippingDetailShippingIdIndexRoute
  '/product-management/attributes/group/$groupId/': typeof AuthorizeProductManagementAttributesGroupGroupIdIndexRoute
  '/product-management/attributes/library/$libraryId/': typeof AuthorizeProductManagementAttributesLibraryLibraryIdIndexRoute
  '/product-management/prints/location/$locationId/': typeof AuthorizeProductManagementPrintsLocationLocationIdIndexRoute
  '/product-management/prints/type/$typeId/': typeof AuthorizeProductManagementPrintsTypeTypeIdIndexRoute
  '/system/teams/$teamId/details/': typeof AuthorizeSystemTeamsTeamIdDetailsIndexRoute
  '/system/teams/$teamId/g-credits/': typeof AuthorizeSystemTeamsTeamIdGCreditsIndexRoute
  '/system/teams/$teamId/payment-methods/': typeof AuthorizeSystemTeamsTeamIdPaymentMethodsIndexRoute
  '/system/teams/$teamId/store/': typeof AuthorizeSystemTeamsTeamIdStoreIndexRoute
  '/system/teams/$teamId/transactions/': typeof AuthorizeSystemTeamsTeamIdTransactionsIndexRoute
  '/system/teams/$teamId/general/': typeof AuthorizeSystemTeamsTeamIdconfigGeneralIndexRoute
  '/system/teams/$teamId/print-type/': typeof AuthorizeSystemTeamsTeamIdconfigPrintTypeIndexRoute
  '/system/teams/$teamId/logs/import-orders/': typeof AuthorizeSystemTeamsTeamIdLogsImportOrdersIndexRoute
  '/system/teams/$teamId/store/$storeId/': typeof AuthorizeSystemTeamsTeamIdStoreStoreIdIndexRoute
  '/system/teams/$teamId/transactions/$txnId/': typeof AuthorizeSystemTeamsTeamIdTransactionsTxnIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthorizeIndexRoute
  '/permission': typeof PermissionRoute
  '/dev': typeof AuthorizeDevRouteWithChildren
  '/users/create': typeof AuthorizeUsersCreateRoute
  '/dashboard': typeof AuthorizeDashboardIndexRoute
  '/product-management': typeof AuthorizeProductManagementIndexRoute
  '/users': typeof AuthorizeUsersIndexRoute
  '/login': typeof UnauthorizeLoginIndexRoute
  '/global-configuration/pricing-management/create-pricing-rule': typeof AuthorizeGlobalConfigurationPricingManagementCreatePricingRuleRoute
  '/global-configuration/tier-management/tier-update-logs': typeof AuthorizeGlobalConfigurationTierManagementTierUpdateLogsRoute
  '/global-configuration/tier-management/update-team-tier': typeof AuthorizeGlobalConfigurationTierManagementUpdateTeamTierRoute
  '/system/members/new-user': typeof AuthorizeSystemMembersNewUserRoute
  '/system/members/permission': typeof AuthorizeSystemMembersPermissionRoute
  '/dev/migration': typeof AuthorizeDevMigrationIndexRoute
  '/dev/open-features': typeof AuthorizeDevOpenFeaturesIndexRoute
  '/dev/sync': typeof AuthorizeDevSyncIndexRoute
  '/finance/deposit': typeof AuthorizeFinanceDepositIndexRoute
  '/finance/payment-request': typeof AuthorizeFinancePaymentRequestIndexRoute
  '/finance/transactions': typeof AuthorizeFinanceTransactionsIndexRoute
  '/fulfillment/shipping-plans': typeof AuthorizeFulfillmentShippingPlansIndexRoute
  '/fulfillment/transactions': typeof AuthorizeFulfillmentTransactionsIndexRoute
  '/global-configuration/finance': typeof AuthorizeGlobalConfigurationFinanceIndexRoute
  '/global-configuration/pricing-management': typeof AuthorizeGlobalConfigurationPricingManagementIndexRoute
  '/global-configuration/rush-order': typeof AuthorizeGlobalConfigurationRushOrderIndexRoute
  '/global-configuration/tier-management': typeof AuthorizeGlobalConfigurationTierManagementIndexRoute
  '/logs/call-logs': typeof AuthorizeLogsCallLogsIndexRoute
  '/logs/export-transactions': typeof AuthorizeLogsExportTransactionsIndexRoute
  '/logs/payment-logs': typeof AuthorizeLogsPaymentLogsIndexRoute
  '/order/$orderId': typeof AuthorizeOrderOrderIdIndexRoute
  '/order/all-orders': typeof AuthorizeOrderAllOrdersIndexRoute
  '/order/draft-orders': typeof AuthorizeOrderDraftOrdersIndexRoute
  '/order/error-orders': typeof AuthorizeOrderErrorOrdersIndexRoute
  '/order/sale-orders': typeof AuthorizeOrderSaleOrdersIndexRoute
  '/product-management/attributes': typeof AuthorizeProductManagementAttributesIndexRoute
  '/product-management/categories': typeof AuthorizeProductManagementCategoriesIndexRoute
  '/product-management/options': typeof AuthorizeProductManagementOptionsIndexRoute
  '/product-management/prints': typeof AuthorizeProductManagementPrintsIndexRoute
  '/product-management/products': typeof AuthorizeProductManagementProductsIndexRoute
  '/product-management/variants': typeof AuthorizeProductManagementVariantsIndexRoute
  '/system/members': typeof AuthorizeSystemMembersIndexRoute
  '/system/permissions': typeof AuthorizeSystemPermissionsIndexRoute
  '/system/teams': typeof AuthorizeSystemTeamsIndexRoute
  '/finance/transactions/$transactionId': typeof AuthorizeFinanceTransactionsTransactionIdIndexRoute
  '/global-configuration/pricing-management/$customId': typeof AuthorizeGlobalConfigurationPricingManagementCustomIdIndexRoute
  '/order/draft-orders/$orderId': typeof AuthorizeOrderDraftOrdersOrderIdIndexRoute
  '/product-management/attributes/group': typeof AuthorizeProductManagementAttributesGroupIndexRoute
  '/product-management/attributes/library': typeof AuthorizeProductManagementAttributesLibraryIndexRoute
  '/product-management/categories/$categoryId': typeof AuthorizeProductManagementCategoriesCategoryIdIndexRoute
  '/product-management/prints/location': typeof AuthorizeProductManagementPrintsLocationIndexRoute
  '/product-management/prints/type': typeof AuthorizeProductManagementPrintsTypeIndexRoute
  '/product-management/products/$productId': typeof AuthorizeProductManagementProductsProductIdIndexRoute
  '/system/teams/$teamId': typeof AuthorizeSystemTeamsTeamIdIndexRoute
  '/system/teams/$teamId/g-credits/enable': typeof AuthorizeSystemTeamsTeamIdGCreditsEnableRoute
  '/finance/transactions/$transactionId/invoice': typeof AuthorizeFinanceTransactionsTransactionIdInvoiceIndexRoute
  '/fulfillment/shipping-plans/$shippingId': typeof AuthorizeFulfillmentShippingPlansshippingDetailShippingIdIndexRoute
  '/product-management/attributes/group/$groupId': typeof AuthorizeProductManagementAttributesGroupGroupIdIndexRoute
  '/product-management/attributes/library/$libraryId': typeof AuthorizeProductManagementAttributesLibraryLibraryIdIndexRoute
  '/product-management/prints/location/$locationId': typeof AuthorizeProductManagementPrintsLocationLocationIdIndexRoute
  '/product-management/prints/type/$typeId': typeof AuthorizeProductManagementPrintsTypeTypeIdIndexRoute
  '/system/teams/$teamId/details': typeof AuthorizeSystemTeamsTeamIdDetailsIndexRoute
  '/system/teams/$teamId/g-credits': typeof AuthorizeSystemTeamsTeamIdGCreditsIndexRoute
  '/system/teams/$teamId/payment-methods': typeof AuthorizeSystemTeamsTeamIdPaymentMethodsIndexRoute
  '/system/teams/$teamId/store': typeof AuthorizeSystemTeamsTeamIdStoreIndexRoute
  '/system/teams/$teamId/transactions': typeof AuthorizeSystemTeamsTeamIdTransactionsIndexRoute
  '/system/teams/$teamId/general': typeof AuthorizeSystemTeamsTeamIdconfigGeneralIndexRoute
  '/system/teams/$teamId/print-type': typeof AuthorizeSystemTeamsTeamIdconfigPrintTypeIndexRoute
  '/system/teams/$teamId/logs/import-orders': typeof AuthorizeSystemTeamsTeamIdLogsImportOrdersIndexRoute
  '/system/teams/$teamId/store/$storeId': typeof AuthorizeSystemTeamsTeamIdStoreStoreIdIndexRoute
  '/system/teams/$teamId/transactions/$txnId': typeof AuthorizeSystemTeamsTeamIdTransactionsTxnIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authorize': typeof AuthorizeRouteWithChildren
  '/_unauthorize': typeof UnauthorizeRouteWithChildren
  '/permission': typeof PermissionRoute
  '/_authorize/dev': typeof AuthorizeDevRouteWithChildren
  '/_authorize/': typeof AuthorizeIndexRoute
  '/_authorize/product-management/attributes': typeof AuthorizeProductManagementAttributesRouteRouteWithChildren
  '/_authorize/product-management/prints': typeof AuthorizeProductManagementPrintsRouteRouteWithChildren
  '/_authorize/logs/export-transactions': typeof AuthorizeLogsExportTransactionsRouteWithChildren
  '/_authorize/users/create': typeof AuthorizeUsersCreateRoute
  '/_authorize/dashboard/': typeof AuthorizeDashboardIndexRoute
  '/_authorize/product-management/': typeof AuthorizeProductManagementIndexRoute
  '/_authorize/users/': typeof AuthorizeUsersIndexRoute
  '/_unauthorize/login/': typeof UnauthorizeLoginIndexRoute
  '/_authorize/global-configuration/pricing-management/create-pricing-rule': typeof AuthorizeGlobalConfigurationPricingManagementCreatePricingRuleRoute
  '/_authorize/global-configuration/tier-management/tier-update-logs': typeof AuthorizeGlobalConfigurationTierManagementTierUpdateLogsRoute
  '/_authorize/global-configuration/tier-management/update-team-tier': typeof AuthorizeGlobalConfigurationTierManagementUpdateTeamTierRoute
  '/_authorize/system/members/new-user': typeof AuthorizeSystemMembersNewUserRoute
  '/_authorize/system/members/permission': typeof AuthorizeSystemMembersPermissionRoute
  '/_authorize/dev/migration/': typeof AuthorizeDevMigrationIndexRoute
  '/_authorize/dev/open-features/': typeof AuthorizeDevOpenFeaturesIndexRoute
  '/_authorize/dev/sync/': typeof AuthorizeDevSyncIndexRoute
  '/_authorize/finance/deposit/': typeof AuthorizeFinanceDepositIndexRoute
  '/_authorize/finance/payment-request/': typeof AuthorizeFinancePaymentRequestIndexRoute
  '/_authorize/finance/transactions/': typeof AuthorizeFinanceTransactionsIndexRoute
  '/_authorize/fulfillment/shipping-plans/': typeof AuthorizeFulfillmentShippingPlansIndexRoute
  '/_authorize/fulfillment/transactions/': typeof AuthorizeFulfillmentTransactionsIndexRoute
  '/_authorize/global-configuration/finance/': typeof AuthorizeGlobalConfigurationFinanceIndexRoute
  '/_authorize/global-configuration/pricing-management/': typeof AuthorizeGlobalConfigurationPricingManagementIndexRoute
  '/_authorize/global-configuration/rush-order/': typeof AuthorizeGlobalConfigurationRushOrderIndexRoute
  '/_authorize/global-configuration/tier-management/': typeof AuthorizeGlobalConfigurationTierManagementIndexRoute
  '/_authorize/logs/call-logs/': typeof AuthorizeLogsCallLogsIndexRoute
  '/_authorize/logs/export-transactions/': typeof AuthorizeLogsExportTransactionsIndexRoute
  '/_authorize/logs/payment-logs/': typeof AuthorizeLogsPaymentLogsIndexRoute
  '/_authorize/order/$orderId/': typeof AuthorizeOrderOrderIdIndexRoute
  '/_authorize/order/all-orders/': typeof AuthorizeOrderAllOrdersIndexRoute
  '/_authorize/order/draft-orders/': typeof AuthorizeOrderDraftOrdersIndexRoute
  '/_authorize/order/error-orders/': typeof AuthorizeOrderErrorOrdersIndexRoute
  '/_authorize/order/sale-orders/': typeof AuthorizeOrderSaleOrdersIndexRoute
  '/_authorize/product-management/attributes/': typeof AuthorizeProductManagementAttributesIndexRoute
  '/_authorize/product-management/categories/': typeof AuthorizeProductManagementCategoriesIndexRoute
  '/_authorize/product-management/options/': typeof AuthorizeProductManagementOptionsIndexRoute
  '/_authorize/product-management/prints/': typeof AuthorizeProductManagementPrintsIndexRoute
  '/_authorize/product-management/products/': typeof AuthorizeProductManagementProductsIndexRoute
  '/_authorize/product-management/variants/': typeof AuthorizeProductManagementVariantsIndexRoute
  '/_authorize/system/members/': typeof AuthorizeSystemMembersIndexRoute
  '/_authorize/system/permissions/': typeof AuthorizeSystemPermissionsIndexRoute
  '/_authorize/system/teams/': typeof AuthorizeSystemTeamsIndexRoute
  '/_authorize/finance/transactions/$transactionId/': typeof AuthorizeFinanceTransactionsTransactionIdIndexRoute
  '/_authorize/global-configuration/pricing-management/$customId/': typeof AuthorizeGlobalConfigurationPricingManagementCustomIdIndexRoute
  '/_authorize/order/draft-orders/$orderId/': typeof AuthorizeOrderDraftOrdersOrderIdIndexRoute
  '/_authorize/product-management/attributes/group/': typeof AuthorizeProductManagementAttributesGroupIndexRoute
  '/_authorize/product-management/attributes/library/': typeof AuthorizeProductManagementAttributesLibraryIndexRoute
  '/_authorize/product-management/categories/$categoryId/': typeof AuthorizeProductManagementCategoriesCategoryIdIndexRoute
  '/_authorize/product-management/prints/location/': typeof AuthorizeProductManagementPrintsLocationIndexRoute
  '/_authorize/product-management/prints/type/': typeof AuthorizeProductManagementPrintsTypeIndexRoute
  '/_authorize/product-management/products/$productId/': typeof AuthorizeProductManagementProductsProductIdIndexRoute
  '/_authorize/system/teams/$teamId/': typeof AuthorizeSystemTeamsTeamIdIndexRoute
  '/_authorize/system/teams/$teamId/g-credits/enable': typeof AuthorizeSystemTeamsTeamIdGCreditsEnableRoute
  '/_authorize/finance/transactions/$transactionId/invoice/': typeof AuthorizeFinanceTransactionsTransactionIdInvoiceIndexRoute
  '/_authorize/fulfillment/shipping-plans/(shipping-detail)/$shippingId/': typeof AuthorizeFulfillmentShippingPlansshippingDetailShippingIdIndexRoute
  '/_authorize/product-management/attributes/group/$groupId/': typeof AuthorizeProductManagementAttributesGroupGroupIdIndexRoute
  '/_authorize/product-management/attributes/library/$libraryId/': typeof AuthorizeProductManagementAttributesLibraryLibraryIdIndexRoute
  '/_authorize/product-management/prints/location/$locationId/': typeof AuthorizeProductManagementPrintsLocationLocationIdIndexRoute
  '/_authorize/product-management/prints/type/$typeId/': typeof AuthorizeProductManagementPrintsTypeTypeIdIndexRoute
  '/_authorize/system/teams/$teamId/details/': typeof AuthorizeSystemTeamsTeamIdDetailsIndexRoute
  '/_authorize/system/teams/$teamId/g-credits/': typeof AuthorizeSystemTeamsTeamIdGCreditsIndexRoute
  '/_authorize/system/teams/$teamId/payment-methods/': typeof AuthorizeSystemTeamsTeamIdPaymentMethodsIndexRoute
  '/_authorize/system/teams/$teamId/store/': typeof AuthorizeSystemTeamsTeamIdStoreIndexRoute
  '/_authorize/system/teams/$teamId/transactions/': typeof AuthorizeSystemTeamsTeamIdTransactionsIndexRoute
  '/_authorize/system/teams/$teamId/(config)/general/': typeof AuthorizeSystemTeamsTeamIdconfigGeneralIndexRoute
  '/_authorize/system/teams/$teamId/(config)/print-type/': typeof AuthorizeSystemTeamsTeamIdconfigPrintTypeIndexRoute
  '/_authorize/system/teams/$teamId/logs/import-orders/': typeof AuthorizeSystemTeamsTeamIdLogsImportOrdersIndexRoute
  '/_authorize/system/teams/$teamId/store/$storeId/': typeof AuthorizeSystemTeamsTeamIdStoreStoreIdIndexRoute
  '/_authorize/system/teams/$teamId/transactions/$txnId/': typeof AuthorizeSystemTeamsTeamIdTransactionsTxnIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/permission'
    | '/dev'
    | '/product-management/attributes'
    | '/product-management/prints'
    | '/logs/export-transactions'
    | '/users/create'
    | '/dashboard/'
    | '/product-management/'
    | '/users/'
    | '/login/'
    | '/global-configuration/pricing-management/create-pricing-rule'
    | '/global-configuration/tier-management/tier-update-logs'
    | '/global-configuration/tier-management/update-team-tier'
    | '/system/members/new-user'
    | '/system/members/permission'
    | '/dev/migration/'
    | '/dev/open-features/'
    | '/dev/sync/'
    | '/finance/deposit/'
    | '/finance/payment-request/'
    | '/finance/transactions/'
    | '/fulfillment/shipping-plans/'
    | '/fulfillment/transactions/'
    | '/global-configuration/finance/'
    | '/global-configuration/pricing-management/'
    | '/global-configuration/rush-order/'
    | '/global-configuration/tier-management/'
    | '/logs/call-logs/'
    | '/logs/export-transactions/'
    | '/logs/payment-logs/'
    | '/order/$orderId/'
    | '/order/all-orders/'
    | '/order/draft-orders/'
    | '/order/error-orders/'
    | '/order/sale-orders/'
    | '/product-management/attributes/'
    | '/product-management/categories/'
    | '/product-management/options/'
    | '/product-management/prints/'
    | '/product-management/products/'
    | '/product-management/variants/'
    | '/system/members/'
    | '/system/permissions/'
    | '/system/teams/'
    | '/finance/transactions/$transactionId/'
    | '/global-configuration/pricing-management/$customId/'
    | '/order/draft-orders/$orderId/'
    | '/product-management/attributes/group/'
    | '/product-management/attributes/library/'
    | '/product-management/categories/$categoryId/'
    | '/product-management/prints/location/'
    | '/product-management/prints/type/'
    | '/product-management/products/$productId/'
    | '/system/teams/$teamId/'
    | '/system/teams/$teamId/g-credits/enable'
    | '/finance/transactions/$transactionId/invoice/'
    | '/fulfillment/shipping-plans/$shippingId/'
    | '/product-management/attributes/group/$groupId/'
    | '/product-management/attributes/library/$libraryId/'
    | '/product-management/prints/location/$locationId/'
    | '/product-management/prints/type/$typeId/'
    | '/system/teams/$teamId/details/'
    | '/system/teams/$teamId/g-credits/'
    | '/system/teams/$teamId/payment-methods/'
    | '/system/teams/$teamId/store/'
    | '/system/teams/$teamId/transactions/'
    | '/system/teams/$teamId/general/'
    | '/system/teams/$teamId/print-type/'
    | '/system/teams/$teamId/logs/import-orders/'
    | '/system/teams/$teamId/store/$storeId/'
    | '/system/teams/$teamId/transactions/$txnId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/permission'
    | '/dev'
    | '/users/create'
    | '/dashboard'
    | '/product-management'
    | '/users'
    | '/login'
    | '/global-configuration/pricing-management/create-pricing-rule'
    | '/global-configuration/tier-management/tier-update-logs'
    | '/global-configuration/tier-management/update-team-tier'
    | '/system/members/new-user'
    | '/system/members/permission'
    | '/dev/migration'
    | '/dev/open-features'
    | '/dev/sync'
    | '/finance/deposit'
    | '/finance/payment-request'
    | '/finance/transactions'
    | '/fulfillment/shipping-plans'
    | '/fulfillment/transactions'
    | '/global-configuration/finance'
    | '/global-configuration/pricing-management'
    | '/global-configuration/rush-order'
    | '/global-configuration/tier-management'
    | '/logs/call-logs'
    | '/logs/export-transactions'
    | '/logs/payment-logs'
    | '/order/$orderId'
    | '/order/all-orders'
    | '/order/draft-orders'
    | '/order/error-orders'
    | '/order/sale-orders'
    | '/product-management/attributes'
    | '/product-management/categories'
    | '/product-management/options'
    | '/product-management/prints'
    | '/product-management/products'
    | '/product-management/variants'
    | '/system/members'
    | '/system/permissions'
    | '/system/teams'
    | '/finance/transactions/$transactionId'
    | '/global-configuration/pricing-management/$customId'
    | '/order/draft-orders/$orderId'
    | '/product-management/attributes/group'
    | '/product-management/attributes/library'
    | '/product-management/categories/$categoryId'
    | '/product-management/prints/location'
    | '/product-management/prints/type'
    | '/product-management/products/$productId'
    | '/system/teams/$teamId'
    | '/system/teams/$teamId/g-credits/enable'
    | '/finance/transactions/$transactionId/invoice'
    | '/fulfillment/shipping-plans/$shippingId'
    | '/product-management/attributes/group/$groupId'
    | '/product-management/attributes/library/$libraryId'
    | '/product-management/prints/location/$locationId'
    | '/product-management/prints/type/$typeId'
    | '/system/teams/$teamId/details'
    | '/system/teams/$teamId/g-credits'
    | '/system/teams/$teamId/payment-methods'
    | '/system/teams/$teamId/store'
    | '/system/teams/$teamId/transactions'
    | '/system/teams/$teamId/general'
    | '/system/teams/$teamId/print-type'
    | '/system/teams/$teamId/logs/import-orders'
    | '/system/teams/$teamId/store/$storeId'
    | '/system/teams/$teamId/transactions/$txnId'
  id:
    | '__root__'
    | '/_authorize'
    | '/_unauthorize'
    | '/permission'
    | '/_authorize/dev'
    | '/_authorize/'
    | '/_authorize/product-management/attributes'
    | '/_authorize/product-management/prints'
    | '/_authorize/logs/export-transactions'
    | '/_authorize/users/create'
    | '/_authorize/dashboard/'
    | '/_authorize/product-management/'
    | '/_authorize/users/'
    | '/_unauthorize/login/'
    | '/_authorize/global-configuration/pricing-management/create-pricing-rule'
    | '/_authorize/global-configuration/tier-management/tier-update-logs'
    | '/_authorize/global-configuration/tier-management/update-team-tier'
    | '/_authorize/system/members/new-user'
    | '/_authorize/system/members/permission'
    | '/_authorize/dev/migration/'
    | '/_authorize/dev/open-features/'
    | '/_authorize/dev/sync/'
    | '/_authorize/finance/deposit/'
    | '/_authorize/finance/payment-request/'
    | '/_authorize/finance/transactions/'
    | '/_authorize/fulfillment/shipping-plans/'
    | '/_authorize/fulfillment/transactions/'
    | '/_authorize/global-configuration/finance/'
    | '/_authorize/global-configuration/pricing-management/'
    | '/_authorize/global-configuration/rush-order/'
    | '/_authorize/global-configuration/tier-management/'
    | '/_authorize/logs/call-logs/'
    | '/_authorize/logs/export-transactions/'
    | '/_authorize/logs/payment-logs/'
    | '/_authorize/order/$orderId/'
    | '/_authorize/order/all-orders/'
    | '/_authorize/order/draft-orders/'
    | '/_authorize/order/error-orders/'
    | '/_authorize/order/sale-orders/'
    | '/_authorize/product-management/attributes/'
    | '/_authorize/product-management/categories/'
    | '/_authorize/product-management/options/'
    | '/_authorize/product-management/prints/'
    | '/_authorize/product-management/products/'
    | '/_authorize/product-management/variants/'
    | '/_authorize/system/members/'
    | '/_authorize/system/permissions/'
    | '/_authorize/system/teams/'
    | '/_authorize/finance/transactions/$transactionId/'
    | '/_authorize/global-configuration/pricing-management/$customId/'
    | '/_authorize/order/draft-orders/$orderId/'
    | '/_authorize/product-management/attributes/group/'
    | '/_authorize/product-management/attributes/library/'
    | '/_authorize/product-management/categories/$categoryId/'
    | '/_authorize/product-management/prints/location/'
    | '/_authorize/product-management/prints/type/'
    | '/_authorize/product-management/products/$productId/'
    | '/_authorize/system/teams/$teamId/'
    | '/_authorize/system/teams/$teamId/g-credits/enable'
    | '/_authorize/finance/transactions/$transactionId/invoice/'
    | '/_authorize/fulfillment/shipping-plans/(shipping-detail)/$shippingId/'
    | '/_authorize/product-management/attributes/group/$groupId/'
    | '/_authorize/product-management/attributes/library/$libraryId/'
    | '/_authorize/product-management/prints/location/$locationId/'
    | '/_authorize/product-management/prints/type/$typeId/'
    | '/_authorize/system/teams/$teamId/details/'
    | '/_authorize/system/teams/$teamId/g-credits/'
    | '/_authorize/system/teams/$teamId/payment-methods/'
    | '/_authorize/system/teams/$teamId/store/'
    | '/_authorize/system/teams/$teamId/transactions/'
    | '/_authorize/system/teams/$teamId/(config)/general/'
    | '/_authorize/system/teams/$teamId/(config)/print-type/'
    | '/_authorize/system/teams/$teamId/logs/import-orders/'
    | '/_authorize/system/teams/$teamId/store/$storeId/'
    | '/_authorize/system/teams/$teamId/transactions/$txnId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthorizeRoute: typeof AuthorizeRouteWithChildren
  UnauthorizeRoute: typeof UnauthorizeRouteWithChildren
  PermissionRoute: typeof PermissionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/permission': {
      id: '/permission'
      path: '/permission'
      fullPath: '/permission'
      preLoaderRoute: typeof PermissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthorize': {
      id: '/_unauthorize'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UnauthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authorize': {
      id: '/_authorize'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authorize/': {
      id: '/_authorize/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthorizeIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/dev': {
      id: '/_authorize/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof AuthorizeDevRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_unauthorize/login/': {
      id: '/_unauthorize/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof UnauthorizeLoginIndexRouteImport
      parentRoute: typeof UnauthorizeRoute
    }
    '/_authorize/users/': {
      id: '/_authorize/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthorizeUsersIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/product-management/': {
      id: '/_authorize/product-management/'
      path: '/product-management'
      fullPath: '/product-management/'
      preLoaderRoute: typeof AuthorizeProductManagementIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/dashboard/': {
      id: '/_authorize/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthorizeDashboardIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/users/create': {
      id: '/_authorize/users/create'
      path: '/users/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof AuthorizeUsersCreateRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/logs/export-transactions': {
      id: '/_authorize/logs/export-transactions'
      path: '/logs/export-transactions'
      fullPath: '/logs/export-transactions'
      preLoaderRoute: typeof AuthorizeLogsExportTransactionsRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/product-management/prints': {
      id: '/_authorize/product-management/prints'
      path: '/product-management/prints'
      fullPath: '/product-management/prints'
      preLoaderRoute: typeof AuthorizeProductManagementPrintsRouteRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/product-management/attributes': {
      id: '/_authorize/product-management/attributes'
      path: '/product-management/attributes'
      fullPath: '/product-management/attributes'
      preLoaderRoute: typeof AuthorizeProductManagementAttributesRouteRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/system/teams/': {
      id: '/_authorize/system/teams/'
      path: '/system/teams'
      fullPath: '/system/teams/'
      preLoaderRoute: typeof AuthorizeSystemTeamsIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/system/permissions/': {
      id: '/_authorize/system/permissions/'
      path: '/system/permissions'
      fullPath: '/system/permissions/'
      preLoaderRoute: typeof AuthorizeSystemPermissionsIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/system/members/': {
      id: '/_authorize/system/members/'
      path: '/system/members'
      fullPath: '/system/members/'
      preLoaderRoute: typeof AuthorizeSystemMembersIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/product-management/variants/': {
      id: '/_authorize/product-management/variants/'
      path: '/product-management/variants'
      fullPath: '/product-management/variants/'
      preLoaderRoute: typeof AuthorizeProductManagementVariantsIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/product-management/products/': {
      id: '/_authorize/product-management/products/'
      path: '/product-management/products'
      fullPath: '/product-management/products/'
      preLoaderRoute: typeof AuthorizeProductManagementProductsIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/product-management/prints/': {
      id: '/_authorize/product-management/prints/'
      path: '/'
      fullPath: '/product-management/prints/'
      preLoaderRoute: typeof AuthorizeProductManagementPrintsIndexRouteImport
      parentRoute: typeof AuthorizeProductManagementPrintsRouteRoute
    }
    '/_authorize/product-management/options/': {
      id: '/_authorize/product-management/options/'
      path: '/product-management/options'
      fullPath: '/product-management/options/'
      preLoaderRoute: typeof AuthorizeProductManagementOptionsIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/product-management/categories/': {
      id: '/_authorize/product-management/categories/'
      path: '/product-management/categories'
      fullPath: '/product-management/categories/'
      preLoaderRoute: typeof AuthorizeProductManagementCategoriesIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/product-management/attributes/': {
      id: '/_authorize/product-management/attributes/'
      path: '/'
      fullPath: '/product-management/attributes/'
      preLoaderRoute: typeof AuthorizeProductManagementAttributesIndexRouteImport
      parentRoute: typeof AuthorizeProductManagementAttributesRouteRoute
    }
    '/_authorize/order/sale-orders/': {
      id: '/_authorize/order/sale-orders/'
      path: '/order/sale-orders'
      fullPath: '/order/sale-orders/'
      preLoaderRoute: typeof AuthorizeOrderSaleOrdersIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/order/error-orders/': {
      id: '/_authorize/order/error-orders/'
      path: '/order/error-orders'
      fullPath: '/order/error-orders/'
      preLoaderRoute: typeof AuthorizeOrderErrorOrdersIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/order/draft-orders/': {
      id: '/_authorize/order/draft-orders/'
      path: '/order/draft-orders'
      fullPath: '/order/draft-orders/'
      preLoaderRoute: typeof AuthorizeOrderDraftOrdersIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/order/all-orders/': {
      id: '/_authorize/order/all-orders/'
      path: '/order/all-orders'
      fullPath: '/order/all-orders/'
      preLoaderRoute: typeof AuthorizeOrderAllOrdersIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/order/$orderId/': {
      id: '/_authorize/order/$orderId/'
      path: '/order/$orderId'
      fullPath: '/order/$orderId/'
      preLoaderRoute: typeof AuthorizeOrderOrderIdIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/logs/payment-logs/': {
      id: '/_authorize/logs/payment-logs/'
      path: '/logs/payment-logs'
      fullPath: '/logs/payment-logs/'
      preLoaderRoute: typeof AuthorizeLogsPaymentLogsIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/logs/export-transactions/': {
      id: '/_authorize/logs/export-transactions/'
      path: '/'
      fullPath: '/logs/export-transactions/'
      preLoaderRoute: typeof AuthorizeLogsExportTransactionsIndexRouteImport
      parentRoute: typeof AuthorizeLogsExportTransactionsRoute
    }
    '/_authorize/logs/call-logs/': {
      id: '/_authorize/logs/call-logs/'
      path: '/logs/call-logs'
      fullPath: '/logs/call-logs/'
      preLoaderRoute: typeof AuthorizeLogsCallLogsIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/global-configuration/tier-management/': {
      id: '/_authorize/global-configuration/tier-management/'
      path: '/global-configuration/tier-management'
      fullPath: '/global-configuration/tier-management/'
      preLoaderRoute: typeof AuthorizeGlobalConfigurationTierManagementIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/global-configuration/rush-order/': {
      id: '/_authorize/global-configuration/rush-order/'
      path: '/global-configuration/rush-order'
      fullPath: '/global-configuration/rush-order/'
      preLoaderRoute: typeof AuthorizeGlobalConfigurationRushOrderIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/global-configuration/pricing-management/': {
      id: '/_authorize/global-configuration/pricing-management/'
      path: '/global-configuration/pricing-management'
      fullPath: '/global-configuration/pricing-management/'
      preLoaderRoute: typeof AuthorizeGlobalConfigurationPricingManagementIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/global-configuration/finance/': {
      id: '/_authorize/global-configuration/finance/'
      path: '/global-configuration/finance'
      fullPath: '/global-configuration/finance/'
      preLoaderRoute: typeof AuthorizeGlobalConfigurationFinanceIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/fulfillment/transactions/': {
      id: '/_authorize/fulfillment/transactions/'
      path: '/fulfillment/transactions'
      fullPath: '/fulfillment/transactions/'
      preLoaderRoute: typeof AuthorizeFulfillmentTransactionsIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/fulfillment/shipping-plans/': {
      id: '/_authorize/fulfillment/shipping-plans/'
      path: '/fulfillment/shipping-plans'
      fullPath: '/fulfillment/shipping-plans/'
      preLoaderRoute: typeof AuthorizeFulfillmentShippingPlansIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/finance/transactions/': {
      id: '/_authorize/finance/transactions/'
      path: '/finance/transactions'
      fullPath: '/finance/transactions/'
      preLoaderRoute: typeof AuthorizeFinanceTransactionsIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/finance/payment-request/': {
      id: '/_authorize/finance/payment-request/'
      path: '/finance/payment-request'
      fullPath: '/finance/payment-request/'
      preLoaderRoute: typeof AuthorizeFinancePaymentRequestIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/finance/deposit/': {
      id: '/_authorize/finance/deposit/'
      path: '/finance/deposit'
      fullPath: '/finance/deposit/'
      preLoaderRoute: typeof AuthorizeFinanceDepositIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/dev/sync/': {
      id: '/_authorize/dev/sync/'
      path: '/sync'
      fullPath: '/dev/sync/'
      preLoaderRoute: typeof AuthorizeDevSyncIndexRouteImport
      parentRoute: typeof AuthorizeDevRoute
    }
    '/_authorize/dev/open-features/': {
      id: '/_authorize/dev/open-features/'
      path: '/open-features'
      fullPath: '/dev/open-features/'
      preLoaderRoute: typeof AuthorizeDevOpenFeaturesIndexRouteImport
      parentRoute: typeof AuthorizeDevRoute
    }
    '/_authorize/dev/migration/': {
      id: '/_authorize/dev/migration/'
      path: '/migration'
      fullPath: '/dev/migration/'
      preLoaderRoute: typeof AuthorizeDevMigrationIndexRouteImport
      parentRoute: typeof AuthorizeDevRoute
    }
    '/_authorize/system/members/permission': {
      id: '/_authorize/system/members/permission'
      path: '/system/members/permission'
      fullPath: '/system/members/permission'
      preLoaderRoute: typeof AuthorizeSystemMembersPermissionRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/system/members/new-user': {
      id: '/_authorize/system/members/new-user'
      path: '/system/members/new-user'
      fullPath: '/system/members/new-user'
      preLoaderRoute: typeof AuthorizeSystemMembersNewUserRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/global-configuration/tier-management/update-team-tier': {
      id: '/_authorize/global-configuration/tier-management/update-team-tier'
      path: '/global-configuration/tier-management/update-team-tier'
      fullPath: '/global-configuration/tier-management/update-team-tier'
      preLoaderRoute: typeof AuthorizeGlobalConfigurationTierManagementUpdateTeamTierRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/global-configuration/tier-management/tier-update-logs': {
      id: '/_authorize/global-configuration/tier-management/tier-update-logs'
      path: '/global-configuration/tier-management/tier-update-logs'
      fullPath: '/global-configuration/tier-management/tier-update-logs'
      preLoaderRoute: typeof AuthorizeGlobalConfigurationTierManagementTierUpdateLogsRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/global-configuration/pricing-management/create-pricing-rule': {
      id: '/_authorize/global-configuration/pricing-management/create-pricing-rule'
      path: '/global-configuration/pricing-management/create-pricing-rule'
      fullPath: '/global-configuration/pricing-management/create-pricing-rule'
      preLoaderRoute: typeof AuthorizeGlobalConfigurationPricingManagementCreatePricingRuleRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/system/teams/$teamId/': {
      id: '/_authorize/system/teams/$teamId/'
      path: '/system/teams/$teamId'
      fullPath: '/system/teams/$teamId/'
      preLoaderRoute: typeof AuthorizeSystemTeamsTeamIdIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/product-management/products/$productId/': {
      id: '/_authorize/product-management/products/$productId/'
      path: '/product-management/products/$productId'
      fullPath: '/product-management/products/$productId/'
      preLoaderRoute: typeof AuthorizeProductManagementProductsProductIdIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/product-management/prints/type/': {
      id: '/_authorize/product-management/prints/type/'
      path: '/type'
      fullPath: '/product-management/prints/type/'
      preLoaderRoute: typeof AuthorizeProductManagementPrintsTypeIndexRouteImport
      parentRoute: typeof AuthorizeProductManagementPrintsRouteRoute
    }
    '/_authorize/product-management/prints/location/': {
      id: '/_authorize/product-management/prints/location/'
      path: '/location'
      fullPath: '/product-management/prints/location/'
      preLoaderRoute: typeof AuthorizeProductManagementPrintsLocationIndexRouteImport
      parentRoute: typeof AuthorizeProductManagementPrintsRouteRoute
    }
    '/_authorize/product-management/categories/$categoryId/': {
      id: '/_authorize/product-management/categories/$categoryId/'
      path: '/product-management/categories/$categoryId'
      fullPath: '/product-management/categories/$categoryId/'
      preLoaderRoute: typeof AuthorizeProductManagementCategoriesCategoryIdIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/product-management/attributes/library/': {
      id: '/_authorize/product-management/attributes/library/'
      path: '/library'
      fullPath: '/product-management/attributes/library/'
      preLoaderRoute: typeof AuthorizeProductManagementAttributesLibraryIndexRouteImport
      parentRoute: typeof AuthorizeProductManagementAttributesRouteRoute
    }
    '/_authorize/product-management/attributes/group/': {
      id: '/_authorize/product-management/attributes/group/'
      path: '/group'
      fullPath: '/product-management/attributes/group/'
      preLoaderRoute: typeof AuthorizeProductManagementAttributesGroupIndexRouteImport
      parentRoute: typeof AuthorizeProductManagementAttributesRouteRoute
    }
    '/_authorize/order/draft-orders/$orderId/': {
      id: '/_authorize/order/draft-orders/$orderId/'
      path: '/order/draft-orders/$orderId'
      fullPath: '/order/draft-orders/$orderId/'
      preLoaderRoute: typeof AuthorizeOrderDraftOrdersOrderIdIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/global-configuration/pricing-management/$customId/': {
      id: '/_authorize/global-configuration/pricing-management/$customId/'
      path: '/global-configuration/pricing-management/$customId'
      fullPath: '/global-configuration/pricing-management/$customId/'
      preLoaderRoute: typeof AuthorizeGlobalConfigurationPricingManagementCustomIdIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/finance/transactions/$transactionId/': {
      id: '/_authorize/finance/transactions/$transactionId/'
      path: '/finance/transactions/$transactionId'
      fullPath: '/finance/transactions/$transactionId/'
      preLoaderRoute: typeof AuthorizeFinanceTransactionsTransactionIdIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/system/teams/$teamId/transactions/': {
      id: '/_authorize/system/teams/$teamId/transactions/'
      path: '/system/teams/$teamId/transactions'
      fullPath: '/system/teams/$teamId/transactions/'
      preLoaderRoute: typeof AuthorizeSystemTeamsTeamIdTransactionsIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/system/teams/$teamId/store/': {
      id: '/_authorize/system/teams/$teamId/store/'
      path: '/system/teams/$teamId/store'
      fullPath: '/system/teams/$teamId/store/'
      preLoaderRoute: typeof AuthorizeSystemTeamsTeamIdStoreIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/system/teams/$teamId/payment-methods/': {
      id: '/_authorize/system/teams/$teamId/payment-methods/'
      path: '/system/teams/$teamId/payment-methods'
      fullPath: '/system/teams/$teamId/payment-methods/'
      preLoaderRoute: typeof AuthorizeSystemTeamsTeamIdPaymentMethodsIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/system/teams/$teamId/g-credits/': {
      id: '/_authorize/system/teams/$teamId/g-credits/'
      path: '/system/teams/$teamId/g-credits'
      fullPath: '/system/teams/$teamId/g-credits/'
      preLoaderRoute: typeof AuthorizeSystemTeamsTeamIdGCreditsIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/system/teams/$teamId/details/': {
      id: '/_authorize/system/teams/$teamId/details/'
      path: '/system/teams/$teamId/details'
      fullPath: '/system/teams/$teamId/details/'
      preLoaderRoute: typeof AuthorizeSystemTeamsTeamIdDetailsIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/product-management/prints/type/$typeId/': {
      id: '/_authorize/product-management/prints/type/$typeId/'
      path: '/type/$typeId'
      fullPath: '/product-management/prints/type/$typeId/'
      preLoaderRoute: typeof AuthorizeProductManagementPrintsTypeTypeIdIndexRouteImport
      parentRoute: typeof AuthorizeProductManagementPrintsRouteRoute
    }
    '/_authorize/product-management/prints/location/$locationId/': {
      id: '/_authorize/product-management/prints/location/$locationId/'
      path: '/location/$locationId'
      fullPath: '/product-management/prints/location/$locationId/'
      preLoaderRoute: typeof AuthorizeProductManagementPrintsLocationLocationIdIndexRouteImport
      parentRoute: typeof AuthorizeProductManagementPrintsRouteRoute
    }
    '/_authorize/product-management/attributes/library/$libraryId/': {
      id: '/_authorize/product-management/attributes/library/$libraryId/'
      path: '/library/$libraryId'
      fullPath: '/product-management/attributes/library/$libraryId/'
      preLoaderRoute: typeof AuthorizeProductManagementAttributesLibraryLibraryIdIndexRouteImport
      parentRoute: typeof AuthorizeProductManagementAttributesRouteRoute
    }
    '/_authorize/product-management/attributes/group/$groupId/': {
      id: '/_authorize/product-management/attributes/group/$groupId/'
      path: '/group/$groupId'
      fullPath: '/product-management/attributes/group/$groupId/'
      preLoaderRoute: typeof AuthorizeProductManagementAttributesGroupGroupIdIndexRouteImport
      parentRoute: typeof AuthorizeProductManagementAttributesRouteRoute
    }
    '/_authorize/fulfillment/shipping-plans/(shipping-detail)/$shippingId/': {
      id: '/_authorize/fulfillment/shipping-plans/(shipping-detail)/$shippingId/'
      path: '/fulfillment/shipping-plans/$shippingId'
      fullPath: '/fulfillment/shipping-plans/$shippingId/'
      preLoaderRoute: typeof AuthorizeFulfillmentShippingPlansshippingDetailShippingIdIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/finance/transactions/$transactionId/invoice/': {
      id: '/_authorize/finance/transactions/$transactionId/invoice/'
      path: '/finance/transactions/$transactionId/invoice'
      fullPath: '/finance/transactions/$transactionId/invoice/'
      preLoaderRoute: typeof AuthorizeFinanceTransactionsTransactionIdInvoiceIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/system/teams/$teamId/g-credits/enable': {
      id: '/_authorize/system/teams/$teamId/g-credits/enable'
      path: '/system/teams/$teamId/g-credits/enable'
      fullPath: '/system/teams/$teamId/g-credits/enable'
      preLoaderRoute: typeof AuthorizeSystemTeamsTeamIdGCreditsEnableRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/system/teams/$teamId/transactions/$txnId/': {
      id: '/_authorize/system/teams/$teamId/transactions/$txnId/'
      path: '/system/teams/$teamId/transactions/$txnId'
      fullPath: '/system/teams/$teamId/transactions/$txnId/'
      preLoaderRoute: typeof AuthorizeSystemTeamsTeamIdTransactionsTxnIdIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/system/teams/$teamId/store/$storeId/': {
      id: '/_authorize/system/teams/$teamId/store/$storeId/'
      path: '/system/teams/$teamId/store/$storeId'
      fullPath: '/system/teams/$teamId/store/$storeId/'
      preLoaderRoute: typeof AuthorizeSystemTeamsTeamIdStoreStoreIdIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/system/teams/$teamId/logs/import-orders/': {
      id: '/_authorize/system/teams/$teamId/logs/import-orders/'
      path: '/system/teams/$teamId/logs/import-orders'
      fullPath: '/system/teams/$teamId/logs/import-orders/'
      preLoaderRoute: typeof AuthorizeSystemTeamsTeamIdLogsImportOrdersIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/system/teams/$teamId/(config)/print-type/': {
      id: '/_authorize/system/teams/$teamId/(config)/print-type/'
      path: '/system/teams/$teamId/print-type'
      fullPath: '/system/teams/$teamId/print-type/'
      preLoaderRoute: typeof AuthorizeSystemTeamsTeamIdconfigPrintTypeIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
    '/_authorize/system/teams/$teamId/(config)/general/': {
      id: '/_authorize/system/teams/$teamId/(config)/general/'
      path: '/system/teams/$teamId/general'
      fullPath: '/system/teams/$teamId/general/'
      preLoaderRoute: typeof AuthorizeSystemTeamsTeamIdconfigGeneralIndexRouteImport
      parentRoute: typeof AuthorizeRoute
    }
  }
}

interface AuthorizeDevRouteChildren {
  AuthorizeDevMigrationIndexRoute: typeof AuthorizeDevMigrationIndexRoute
  AuthorizeDevOpenFeaturesIndexRoute: typeof AuthorizeDevOpenFeaturesIndexRoute
  AuthorizeDevSyncIndexRoute: typeof AuthorizeDevSyncIndexRoute
}

const AuthorizeDevRouteChildren: AuthorizeDevRouteChildren = {
  AuthorizeDevMigrationIndexRoute: AuthorizeDevMigrationIndexRoute,
  AuthorizeDevOpenFeaturesIndexRoute: AuthorizeDevOpenFeaturesIndexRoute,
  AuthorizeDevSyncIndexRoute: AuthorizeDevSyncIndexRoute,
}

const AuthorizeDevRouteWithChildren = AuthorizeDevRoute._addFileChildren(
  AuthorizeDevRouteChildren,
)

interface AuthorizeProductManagementAttributesRouteRouteChildren {
  AuthorizeProductManagementAttributesIndexRoute: typeof AuthorizeProductManagementAttributesIndexRoute
  AuthorizeProductManagementAttributesGroupIndexRoute: typeof AuthorizeProductManagementAttributesGroupIndexRoute
  AuthorizeProductManagementAttributesLibraryIndexRoute: typeof AuthorizeProductManagementAttributesLibraryIndexRoute
  AuthorizeProductManagementAttributesGroupGroupIdIndexRoute: typeof AuthorizeProductManagementAttributesGroupGroupIdIndexRoute
  AuthorizeProductManagementAttributesLibraryLibraryIdIndexRoute: typeof AuthorizeProductManagementAttributesLibraryLibraryIdIndexRoute
}

const AuthorizeProductManagementAttributesRouteRouteChildren: AuthorizeProductManagementAttributesRouteRouteChildren =
  {
    AuthorizeProductManagementAttributesIndexRoute:
      AuthorizeProductManagementAttributesIndexRoute,
    AuthorizeProductManagementAttributesGroupIndexRoute:
      AuthorizeProductManagementAttributesGroupIndexRoute,
    AuthorizeProductManagementAttributesLibraryIndexRoute:
      AuthorizeProductManagementAttributesLibraryIndexRoute,
    AuthorizeProductManagementAttributesGroupGroupIdIndexRoute:
      AuthorizeProductManagementAttributesGroupGroupIdIndexRoute,
    AuthorizeProductManagementAttributesLibraryLibraryIdIndexRoute:
      AuthorizeProductManagementAttributesLibraryLibraryIdIndexRoute,
  }

const AuthorizeProductManagementAttributesRouteRouteWithChildren =
  AuthorizeProductManagementAttributesRouteRoute._addFileChildren(
    AuthorizeProductManagementAttributesRouteRouteChildren,
  )

interface AuthorizeProductManagementPrintsRouteRouteChildren {
  AuthorizeProductManagementPrintsIndexRoute: typeof AuthorizeProductManagementPrintsIndexRoute
  AuthorizeProductManagementPrintsLocationIndexRoute: typeof AuthorizeProductManagementPrintsLocationIndexRoute
  AuthorizeProductManagementPrintsTypeIndexRoute: typeof AuthorizeProductManagementPrintsTypeIndexRoute
  AuthorizeProductManagementPrintsLocationLocationIdIndexRoute: typeof AuthorizeProductManagementPrintsLocationLocationIdIndexRoute
  AuthorizeProductManagementPrintsTypeTypeIdIndexRoute: typeof AuthorizeProductManagementPrintsTypeTypeIdIndexRoute
}

const AuthorizeProductManagementPrintsRouteRouteChildren: AuthorizeProductManagementPrintsRouteRouteChildren =
  {
    AuthorizeProductManagementPrintsIndexRoute:
      AuthorizeProductManagementPrintsIndexRoute,
    AuthorizeProductManagementPrintsLocationIndexRoute:
      AuthorizeProductManagementPrintsLocationIndexRoute,
    AuthorizeProductManagementPrintsTypeIndexRoute:
      AuthorizeProductManagementPrintsTypeIndexRoute,
    AuthorizeProductManagementPrintsLocationLocationIdIndexRoute:
      AuthorizeProductManagementPrintsLocationLocationIdIndexRoute,
    AuthorizeProductManagementPrintsTypeTypeIdIndexRoute:
      AuthorizeProductManagementPrintsTypeTypeIdIndexRoute,
  }

const AuthorizeProductManagementPrintsRouteRouteWithChildren =
  AuthorizeProductManagementPrintsRouteRoute._addFileChildren(
    AuthorizeProductManagementPrintsRouteRouteChildren,
  )

interface AuthorizeLogsExportTransactionsRouteChildren {
  AuthorizeLogsExportTransactionsIndexRoute: typeof AuthorizeLogsExportTransactionsIndexRoute
}

const AuthorizeLogsExportTransactionsRouteChildren: AuthorizeLogsExportTransactionsRouteChildren =
  {
    AuthorizeLogsExportTransactionsIndexRoute:
      AuthorizeLogsExportTransactionsIndexRoute,
  }

const AuthorizeLogsExportTransactionsRouteWithChildren =
  AuthorizeLogsExportTransactionsRoute._addFileChildren(
    AuthorizeLogsExportTransactionsRouteChildren,
  )

interface AuthorizeRouteChildren {
  AuthorizeDevRoute: typeof AuthorizeDevRouteWithChildren
  AuthorizeIndexRoute: typeof AuthorizeIndexRoute
  AuthorizeProductManagementAttributesRouteRoute: typeof AuthorizeProductManagementAttributesRouteRouteWithChildren
  AuthorizeProductManagementPrintsRouteRoute: typeof AuthorizeProductManagementPrintsRouteRouteWithChildren
  AuthorizeLogsExportTransactionsRoute: typeof AuthorizeLogsExportTransactionsRouteWithChildren
  AuthorizeUsersCreateRoute: typeof AuthorizeUsersCreateRoute
  AuthorizeDashboardIndexRoute: typeof AuthorizeDashboardIndexRoute
  AuthorizeProductManagementIndexRoute: typeof AuthorizeProductManagementIndexRoute
  AuthorizeUsersIndexRoute: typeof AuthorizeUsersIndexRoute
  AuthorizeGlobalConfigurationPricingManagementCreatePricingRuleRoute: typeof AuthorizeGlobalConfigurationPricingManagementCreatePricingRuleRoute
  AuthorizeGlobalConfigurationTierManagementTierUpdateLogsRoute: typeof AuthorizeGlobalConfigurationTierManagementTierUpdateLogsRoute
  AuthorizeGlobalConfigurationTierManagementUpdateTeamTierRoute: typeof AuthorizeGlobalConfigurationTierManagementUpdateTeamTierRoute
  AuthorizeSystemMembersNewUserRoute: typeof AuthorizeSystemMembersNewUserRoute
  AuthorizeSystemMembersPermissionRoute: typeof AuthorizeSystemMembersPermissionRoute
  AuthorizeFinanceDepositIndexRoute: typeof AuthorizeFinanceDepositIndexRoute
  AuthorizeFinancePaymentRequestIndexRoute: typeof AuthorizeFinancePaymentRequestIndexRoute
  AuthorizeFinanceTransactionsIndexRoute: typeof AuthorizeFinanceTransactionsIndexRoute
  AuthorizeFulfillmentShippingPlansIndexRoute: typeof AuthorizeFulfillmentShippingPlansIndexRoute
  AuthorizeFulfillmentTransactionsIndexRoute: typeof AuthorizeFulfillmentTransactionsIndexRoute
  AuthorizeGlobalConfigurationFinanceIndexRoute: typeof AuthorizeGlobalConfigurationFinanceIndexRoute
  AuthorizeGlobalConfigurationPricingManagementIndexRoute: typeof AuthorizeGlobalConfigurationPricingManagementIndexRoute
  AuthorizeGlobalConfigurationRushOrderIndexRoute: typeof AuthorizeGlobalConfigurationRushOrderIndexRoute
  AuthorizeGlobalConfigurationTierManagementIndexRoute: typeof AuthorizeGlobalConfigurationTierManagementIndexRoute
  AuthorizeLogsCallLogsIndexRoute: typeof AuthorizeLogsCallLogsIndexRoute
  AuthorizeLogsPaymentLogsIndexRoute: typeof AuthorizeLogsPaymentLogsIndexRoute
  AuthorizeOrderOrderIdIndexRoute: typeof AuthorizeOrderOrderIdIndexRoute
  AuthorizeOrderAllOrdersIndexRoute: typeof AuthorizeOrderAllOrdersIndexRoute
  AuthorizeOrderDraftOrdersIndexRoute: typeof AuthorizeOrderDraftOrdersIndexRoute
  AuthorizeOrderErrorOrdersIndexRoute: typeof AuthorizeOrderErrorOrdersIndexRoute
  AuthorizeOrderSaleOrdersIndexRoute: typeof AuthorizeOrderSaleOrdersIndexRoute
  AuthorizeProductManagementCategoriesIndexRoute: typeof AuthorizeProductManagementCategoriesIndexRoute
  AuthorizeProductManagementOptionsIndexRoute: typeof AuthorizeProductManagementOptionsIndexRoute
  AuthorizeProductManagementProductsIndexRoute: typeof AuthorizeProductManagementProductsIndexRoute
  AuthorizeProductManagementVariantsIndexRoute: typeof AuthorizeProductManagementVariantsIndexRoute
  AuthorizeSystemMembersIndexRoute: typeof AuthorizeSystemMembersIndexRoute
  AuthorizeSystemPermissionsIndexRoute: typeof AuthorizeSystemPermissionsIndexRoute
  AuthorizeSystemTeamsIndexRoute: typeof AuthorizeSystemTeamsIndexRoute
  AuthorizeFinanceTransactionsTransactionIdIndexRoute: typeof AuthorizeFinanceTransactionsTransactionIdIndexRoute
  AuthorizeGlobalConfigurationPricingManagementCustomIdIndexRoute: typeof AuthorizeGlobalConfigurationPricingManagementCustomIdIndexRoute
  AuthorizeOrderDraftOrdersOrderIdIndexRoute: typeof AuthorizeOrderDraftOrdersOrderIdIndexRoute
  AuthorizeProductManagementCategoriesCategoryIdIndexRoute: typeof AuthorizeProductManagementCategoriesCategoryIdIndexRoute
  AuthorizeProductManagementProductsProductIdIndexRoute: typeof AuthorizeProductManagementProductsProductIdIndexRoute
  AuthorizeSystemTeamsTeamIdIndexRoute: typeof AuthorizeSystemTeamsTeamIdIndexRoute
  AuthorizeSystemTeamsTeamIdGCreditsEnableRoute: typeof AuthorizeSystemTeamsTeamIdGCreditsEnableRoute
  AuthorizeFinanceTransactionsTransactionIdInvoiceIndexRoute: typeof AuthorizeFinanceTransactionsTransactionIdInvoiceIndexRoute
  AuthorizeFulfillmentShippingPlansshippingDetailShippingIdIndexRoute: typeof AuthorizeFulfillmentShippingPlansshippingDetailShippingIdIndexRoute
  AuthorizeSystemTeamsTeamIdDetailsIndexRoute: typeof AuthorizeSystemTeamsTeamIdDetailsIndexRoute
  AuthorizeSystemTeamsTeamIdGCreditsIndexRoute: typeof AuthorizeSystemTeamsTeamIdGCreditsIndexRoute
  AuthorizeSystemTeamsTeamIdPaymentMethodsIndexRoute: typeof AuthorizeSystemTeamsTeamIdPaymentMethodsIndexRoute
  AuthorizeSystemTeamsTeamIdStoreIndexRoute: typeof AuthorizeSystemTeamsTeamIdStoreIndexRoute
  AuthorizeSystemTeamsTeamIdTransactionsIndexRoute: typeof AuthorizeSystemTeamsTeamIdTransactionsIndexRoute
  AuthorizeSystemTeamsTeamIdconfigGeneralIndexRoute: typeof AuthorizeSystemTeamsTeamIdconfigGeneralIndexRoute
  AuthorizeSystemTeamsTeamIdconfigPrintTypeIndexRoute: typeof AuthorizeSystemTeamsTeamIdconfigPrintTypeIndexRoute
  AuthorizeSystemTeamsTeamIdLogsImportOrdersIndexRoute: typeof AuthorizeSystemTeamsTeamIdLogsImportOrdersIndexRoute
  AuthorizeSystemTeamsTeamIdStoreStoreIdIndexRoute: typeof AuthorizeSystemTeamsTeamIdStoreStoreIdIndexRoute
  AuthorizeSystemTeamsTeamIdTransactionsTxnIdIndexRoute: typeof AuthorizeSystemTeamsTeamIdTransactionsTxnIdIndexRoute
}

const AuthorizeRouteChildren: AuthorizeRouteChildren = {
  AuthorizeDevRoute: AuthorizeDevRouteWithChildren,
  AuthorizeIndexRoute: AuthorizeIndexRoute,
  AuthorizeProductManagementAttributesRouteRoute:
    AuthorizeProductManagementAttributesRouteRouteWithChildren,
  AuthorizeProductManagementPrintsRouteRoute:
    AuthorizeProductManagementPrintsRouteRouteWithChildren,
  AuthorizeLogsExportTransactionsRoute:
    AuthorizeLogsExportTransactionsRouteWithChildren,
  AuthorizeUsersCreateRoute: AuthorizeUsersCreateRoute,
  AuthorizeDashboardIndexRoute: AuthorizeDashboardIndexRoute,
  AuthorizeProductManagementIndexRoute: AuthorizeProductManagementIndexRoute,
  AuthorizeUsersIndexRoute: AuthorizeUsersIndexRoute,
  AuthorizeGlobalConfigurationPricingManagementCreatePricingRuleRoute:
    AuthorizeGlobalConfigurationPricingManagementCreatePricingRuleRoute,
  AuthorizeGlobalConfigurationTierManagementTierUpdateLogsRoute:
    AuthorizeGlobalConfigurationTierManagementTierUpdateLogsRoute,
  AuthorizeGlobalConfigurationTierManagementUpdateTeamTierRoute:
    AuthorizeGlobalConfigurationTierManagementUpdateTeamTierRoute,
  AuthorizeSystemMembersNewUserRoute: AuthorizeSystemMembersNewUserRoute,
  AuthorizeSystemMembersPermissionRoute: AuthorizeSystemMembersPermissionRoute,
  AuthorizeFinanceDepositIndexRoute: AuthorizeFinanceDepositIndexRoute,
  AuthorizeFinancePaymentRequestIndexRoute:
    AuthorizeFinancePaymentRequestIndexRoute,
  AuthorizeFinanceTransactionsIndexRoute:
    AuthorizeFinanceTransactionsIndexRoute,
  AuthorizeFulfillmentShippingPlansIndexRoute:
    AuthorizeFulfillmentShippingPlansIndexRoute,
  AuthorizeFulfillmentTransactionsIndexRoute:
    AuthorizeFulfillmentTransactionsIndexRoute,
  AuthorizeGlobalConfigurationFinanceIndexRoute:
    AuthorizeGlobalConfigurationFinanceIndexRoute,
  AuthorizeGlobalConfigurationPricingManagementIndexRoute:
    AuthorizeGlobalConfigurationPricingManagementIndexRoute,
  AuthorizeGlobalConfigurationRushOrderIndexRoute:
    AuthorizeGlobalConfigurationRushOrderIndexRoute,
  AuthorizeGlobalConfigurationTierManagementIndexRoute:
    AuthorizeGlobalConfigurationTierManagementIndexRoute,
  AuthorizeLogsCallLogsIndexRoute: AuthorizeLogsCallLogsIndexRoute,
  AuthorizeLogsPaymentLogsIndexRoute: AuthorizeLogsPaymentLogsIndexRoute,
  AuthorizeOrderOrderIdIndexRoute: AuthorizeOrderOrderIdIndexRoute,
  AuthorizeOrderAllOrdersIndexRoute: AuthorizeOrderAllOrdersIndexRoute,
  AuthorizeOrderDraftOrdersIndexRoute: AuthorizeOrderDraftOrdersIndexRoute,
  AuthorizeOrderErrorOrdersIndexRoute: AuthorizeOrderErrorOrdersIndexRoute,
  AuthorizeOrderSaleOrdersIndexRoute: AuthorizeOrderSaleOrdersIndexRoute,
  AuthorizeProductManagementCategoriesIndexRoute:
    AuthorizeProductManagementCategoriesIndexRoute,
  AuthorizeProductManagementOptionsIndexRoute:
    AuthorizeProductManagementOptionsIndexRoute,
  AuthorizeProductManagementProductsIndexRoute:
    AuthorizeProductManagementProductsIndexRoute,
  AuthorizeProductManagementVariantsIndexRoute:
    AuthorizeProductManagementVariantsIndexRoute,
  AuthorizeSystemMembersIndexRoute: AuthorizeSystemMembersIndexRoute,
  AuthorizeSystemPermissionsIndexRoute: AuthorizeSystemPermissionsIndexRoute,
  AuthorizeSystemTeamsIndexRoute: AuthorizeSystemTeamsIndexRoute,
  AuthorizeFinanceTransactionsTransactionIdIndexRoute:
    AuthorizeFinanceTransactionsTransactionIdIndexRoute,
  AuthorizeGlobalConfigurationPricingManagementCustomIdIndexRoute:
    AuthorizeGlobalConfigurationPricingManagementCustomIdIndexRoute,
  AuthorizeOrderDraftOrdersOrderIdIndexRoute:
    AuthorizeOrderDraftOrdersOrderIdIndexRoute,
  AuthorizeProductManagementCategoriesCategoryIdIndexRoute:
    AuthorizeProductManagementCategoriesCategoryIdIndexRoute,
  AuthorizeProductManagementProductsProductIdIndexRoute:
    AuthorizeProductManagementProductsProductIdIndexRoute,
  AuthorizeSystemTeamsTeamIdIndexRoute: AuthorizeSystemTeamsTeamIdIndexRoute,
  AuthorizeSystemTeamsTeamIdGCreditsEnableRoute:
    AuthorizeSystemTeamsTeamIdGCreditsEnableRoute,
  AuthorizeFinanceTransactionsTransactionIdInvoiceIndexRoute:
    AuthorizeFinanceTransactionsTransactionIdInvoiceIndexRoute,
  AuthorizeFulfillmentShippingPlansshippingDetailShippingIdIndexRoute:
    AuthorizeFulfillmentShippingPlansshippingDetailShippingIdIndexRoute,
  AuthorizeSystemTeamsTeamIdDetailsIndexRoute:
    AuthorizeSystemTeamsTeamIdDetailsIndexRoute,
  AuthorizeSystemTeamsTeamIdGCreditsIndexRoute:
    AuthorizeSystemTeamsTeamIdGCreditsIndexRoute,
  AuthorizeSystemTeamsTeamIdPaymentMethodsIndexRoute:
    AuthorizeSystemTeamsTeamIdPaymentMethodsIndexRoute,
  AuthorizeSystemTeamsTeamIdStoreIndexRoute:
    AuthorizeSystemTeamsTeamIdStoreIndexRoute,
  AuthorizeSystemTeamsTeamIdTransactionsIndexRoute:
    AuthorizeSystemTeamsTeamIdTransactionsIndexRoute,
  AuthorizeSystemTeamsTeamIdconfigGeneralIndexRoute:
    AuthorizeSystemTeamsTeamIdconfigGeneralIndexRoute,
  AuthorizeSystemTeamsTeamIdconfigPrintTypeIndexRoute:
    AuthorizeSystemTeamsTeamIdconfigPrintTypeIndexRoute,
  AuthorizeSystemTeamsTeamIdLogsImportOrdersIndexRoute:
    AuthorizeSystemTeamsTeamIdLogsImportOrdersIndexRoute,
  AuthorizeSystemTeamsTeamIdStoreStoreIdIndexRoute:
    AuthorizeSystemTeamsTeamIdStoreStoreIdIndexRoute,
  AuthorizeSystemTeamsTeamIdTransactionsTxnIdIndexRoute:
    AuthorizeSystemTeamsTeamIdTransactionsTxnIdIndexRoute,
}

const AuthorizeRouteWithChildren = AuthorizeRoute._addFileChildren(
  AuthorizeRouteChildren,
)

interface UnauthorizeRouteChildren {
  UnauthorizeLoginIndexRoute: typeof UnauthorizeLoginIndexRoute
}

const UnauthorizeRouteChildren: UnauthorizeRouteChildren = {
  UnauthorizeLoginIndexRoute: UnauthorizeLoginIndexRoute,
}

const UnauthorizeRouteWithChildren = UnauthorizeRoute._addFileChildren(
  UnauthorizeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthorizeRoute: AuthorizeRouteWithChildren,
  UnauthorizeRoute: UnauthorizeRouteWithChildren,
  PermissionRoute: PermissionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
